//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_SpaceWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UnityEngine.Space));
		L.RegVar("World", new LuaCSFunction(get_World), null);
		L.RegVar("Self", new LuaCSFunction(get_Self), null);
		L.RegFunction("ToInt", new LuaCSFunction(EnumTrait<UnityEngine.Space>.ToInt));
		L.RegFunction("IntToEnum", new LuaCSFunction(EnumTrait<UnityEngine.Space>.IntToEnum));
		L.RegFunction("CompareTo", new LuaCSFunction(EnumTrait<UnityEngine.Space>.CompareTo));
		L.RegFunction("ToString", new LuaCSFunction(EnumTrait<UnityEngine.Space>.ToString));
#if !LUAC_5_3
		L.RegEnumEqualFunction("__eq");
#endif
		L.RegFunction("Equals", new LuaCSFunction(EnumTrait<UnityEngine.Space>.Equals));
		L.RegFunction("__tostring", new LuaCSFunction(EnumTrait<UnityEngine.Space>.ToString));
		L.EndEnum();
		TypeTraits<UnityEngine.Space>.Check = EnumTrait<UnityEngine.Space>.CheckType;
		StackTraits<UnityEngine.Space>.Push = ToLua.PushData<UnityEngine.Space>;
		EnumTrait<UnityEngine.Space>.IntToEnumTransfer = (i) => (UnityEngine.Space)i;
		EnumTrait<UnityEngine.Space>.EnumToInt = (e) => (int)e;
	}


	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_World(IntPtr L)
	{
		ToLua.PushData(L, UnityEngine.Space.World);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Self(IntPtr L)
	{
		ToLua.PushData(L, UnityEngine.Space.Self);
		return 1;
	}
}

