//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_WrapModeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UnityEngine.WrapMode));
		L.RegVar("Once", new LuaCSFunction(get_Once), null);
		L.RegVar("Loop", new LuaCSFunction(get_Loop), null);
		L.RegVar("PingPong", new LuaCSFunction(get_PingPong), null);
		L.RegVar("Default", new LuaCSFunction(get_Default), null);
		L.RegVar("ClampForever", new LuaCSFunction(get_ClampForever), null);
		L.RegVar("Clamp", new LuaCSFunction(get_Clamp), null);
		L.RegFunction("ToInt", new LuaCSFunction(EnumTrait<UnityEngine.WrapMode>.ToInt));
		L.RegFunction("IntToEnum", new LuaCSFunction(EnumTrait<UnityEngine.WrapMode>.IntToEnum));
		L.RegFunction("CompareTo", new LuaCSFunction(EnumTrait<UnityEngine.WrapMode>.CompareTo));
		L.RegFunction("ToString", new LuaCSFunction(EnumTrait<UnityEngine.WrapMode>.ToString));
#if !LUAC_5_3
		L.RegEnumEqualFunction("__eq");
#endif
		L.RegFunction("Equals", new LuaCSFunction(EnumTrait<UnityEngine.WrapMode>.Equals));
		L.RegFunction("__tostring", new LuaCSFunction(EnumTrait<UnityEngine.WrapMode>.ToString));
		L.EndEnum();
		TypeTraits<UnityEngine.WrapMode>.Check = EnumTrait<UnityEngine.WrapMode>.CheckType;
		StackTraits<UnityEngine.WrapMode>.Push = ToLua.PushData<UnityEngine.WrapMode>;
		EnumTrait<UnityEngine.WrapMode>.IntToEnumTransfer = (i) => (UnityEngine.WrapMode)i;
		EnumTrait<UnityEngine.WrapMode>.EnumToInt = (e) => (int)e;
	}


	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Once(IntPtr L)
	{
		ToLua.PushData(L, UnityEngine.WrapMode.Once);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Loop(IntPtr L)
	{
		ToLua.PushData(L, UnityEngine.WrapMode.Loop);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_PingPong(IntPtr L)
	{
		ToLua.PushData(L, UnityEngine.WrapMode.PingPong);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Default(IntPtr L)
	{
		ToLua.PushData(L, UnityEngine.WrapMode.Default);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ClampForever(IntPtr L)
	{
		ToLua.PushData(L, UnityEngine.WrapMode.ClampForever);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Clamp(IntPtr L)
	{
		ToLua.PushData(L, UnityEngine.WrapMode.Clamp);
		return 1;
	}
}

